services:
  db:
    image: postgres:15
    container_name: employee-hierarchy-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

  backend:
    build: ./backend
    container_name: employee-hierarchy-backend
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    # volumes:
    #   - ./backend:/usr/src/app
    ports:
      - "${BACKEND_PORT}:3000"

  frontend:
    build: ./frontend
    container_name: employee-hierarchy-frontend
    env_file:
      - .env
    depends_on:
      - backend
    # volumes:
    #   - ./frontend:/usr/src/app
    ports:
      - "${FRONTEND_PORT}:5173"

volumes:
  postgres_data:
